### ISSUE TITLE
[Suggestion] Rename the repository to "roblox-engine-research"

### ISSUE THREAD

**Issue by byteveil** [koneko/roblox#2]
It allows people to find this repository much easier by including keywords that are relevant to the repository's purpose.

---

You should also add some tags to the repository for better discoverability through topics.

- lua
- luau
- research
- roblox

Users can then find the repository with the search bar by searching `topic:lua` or `topic:roblox topic:research` to narrow their results.

**Comment by koneko** [comment]
i already added some before, but i also added more. ty
